// <auto-generated />
using System;
using Customers.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Customers.Core.Migrations.KeyVault
{
    [DbContext(typeof(KeyVaultDbContext))]
    [Migration("20260719152404_EnvelopeEncryption")]
    partial class EnvelopeEncryption
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Customers.Core.Services.CryptoService.EncryptionKey", b =>
                {
                    b.Property<Guid>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<byte[]>("WrappedKeyMaterial")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("CustomerId");

                    b.ToTable("EncryptionKeys");
                });
#pragma warning restore 612, 618
        }
    }
}
