apiVersion: v1
kind: Secret
metadata:
  name: postgres-orders-secret
  namespace: crypto-shredding
type: Opaque
stringData:
  POSTGRES_DB: ordersdb
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-orders-pvc
  namespace: crypto-shredding
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-orders
  namespace: crypto-shredding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-orders
  template:
    metadata:
      labels:
        app: postgres-orders
    spec:
      containers:
        - name: postgres
          image: postgres:17
          envFrom:
            - secretRef:
                name: postgres-orders-secret
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
          readinessProbe:
            exec:
              command: ["pg_isready", "-U", "postgres"]
            initialDelaySeconds: 3
            periodSeconds: 3
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: postgres-orders-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-orders
  namespace: crypto-shredding
spec:
  selector:
    app: postgres-orders
  ports:
    - port: 5432
      targetPort: 5432
